### ISSUE TITLE
TypeError: Cannot read property 'range' of undefined

### ISSUE THREAD

**Issue by onyegood** [cornflourblue/react-pagination-example#4]
I keep getting the bellow error when tried to implement your pagination code into my react project.
What could be the cause of this error?

TypeError: Cannot read property 'range' of undefined

Pagination.getPager
C:/wamp64/www/React-Project/starter-pack/src/includes/pagination/Pagination.jsx:90
  87 |       var endIndex = Math.min(startIndex + pageSize - 1, totalItems - 1);
  88 | 
  89 |       // create an array of pages to ng-repeat in the pager control
> 90 |       var pages = _.range(startPage, endPage + 1);
  91 | 
  92 |       // return object with all pager properties required by the view
  93 |       return {
View compiled
Pagination.setPage
C:/wamp64/www/React-Project/starter-pack/src/includes/pagination/Pagination.jsx:44
  41 |       }
  42 | 
  43 |       // get new pager object for specified page
> 44 |       pager = this.getPager(items.length, page);
  45 | 
  46 |       // get new page of items from items array
  47 |       var pageOfItems = items.slice(pager.startIndex, pager.endIndex + 1);
View compiled
Pagination.componentWillMount
C:/wamp64/www/React-Project/starter-pack/src/includes/pagination/Pagination.jsx:24
  21 |   componentWillMount() {
  22 |       // set page if items array isn't empty
  23 |       if (this.props.items && this.props.items.length) {
> 24 |           this.setPage(this.props.initialPage);
  25 |       }
  26 |   }
  27 |

**Comment by cornflourblue** [comment]
There was a dependency on lodash / underscore before, I've just removed it so the component will work for you now without lodash.
